---
name: Test PAT Push
on:
  workflow_dispatch:
jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make a test change
        run: echo "# Test $(date)" > test-pat.txt
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add test-pat.txt
          git commit -m "Test PAT push"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
